import { Poppins, Roboto } from 'next/font/google';
import "./globals.css";
import Navbar from './components/navbar';
import Footer from './components/footer';

// Load fonts with specific weights
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['700', '600'], // 700 (Bold) for headings, 600 (SemiBold) for subheadings
  variable: '--font-poppins',
});

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['300'], // 300 (Light) for body text
  variable: '--font-roboto',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable} ${roboto.variable}`}>
      <body className='bg-white text-black '>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
